### PR TITLE
New Feature: xhal & RPC functionality added to gempython

### PR DESCRIPTION
**Pull request by bdorney**
## Description

Requires: https://github.com/cms-gem-daq-project/ctp7_modules/pull/11

Added the following:
- `gempython/tools/amc_user_functions_xhal.py`
- `gempython/tools/optohybrid_user_functions_xhal.py`
- `gempython/tools/vfat_user_functions_xhal.py`
- `gempython/utils/registers_xhal.py`

This provides functionality for using RPC protocol and SW tools in `xhal` and `ctp7_modules` in our python tools.  This is not an exhaustive functionality but is a baseline for scripts in `vfatqc-python-scripts` for v3 electronics testing.

@jsturdy @mexanick 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

Seeks to implement:
- RPC functionaliy, and
- Provide flexible SW that will execute v2b or v3 electronics behavior independent of the user at runtime.

## How Has This Been Tested?

The v3 electronics functionality has been tested in this [E-Log Post](http://cmsonline.cern.ch/cms-elog/1015765).  

I have not yet tested the interaction with `chamber_vfatDACSettings` in `gem-plotting-tools/mapping/chamberInfo.py` for v3 electronics yet.  Pending.

I have not yet tested this on v2b electronics.  Pending. 

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jsturdy** [comment]
Holy hell @bdorney, pretty sure there's no way this goes through!
210 files changed??
Ah, I see what you did... OK, this is going to have to be re-done, but I'll have to think of how to make you re-do it..

**Comment by bdorney** [comment]
I thought I was supposed to push to `develop`...?

**Comment by jsturdy** [comment]
Well, the problem is that you didn't start your development off of `develop`...
I just have to decide when/how to update the develop branch with a host of other changes, then this won't be quite so "aggressive" :)

**Comment by jsturdy** [comment]
Changed target

**Comment by bdorney** [comment]
Initial testing completed, can confirm I am able to perform basic actions:
- configure
- VThreshold1 and CFG_THR_ARM_DAC scans
- scurves
- latency scans

**Pull request merged**
