### PR TITLE
Add default GBT RX phases for long GE1/1 GEBs

### PR DESCRIPTION
**Pull request by lpetre-ulb**
## Description

From today long GE1/1 GEBs will be tested at QC7. Therefore a LUT must be available in order to cope with the "all good phases" case during the GBT RX phase scan. Based on OH&GEB QC experience at ULB good default phases can be deduced.

The following plot summarizes the GBT phase scan result for 20 long GEBs. Phases were read by eye from the plot.

LongGEB

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

`testConnectivity.py` runs with long GEBs and does not write the place holder phase (0).

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by bdorney — APPROVED** [review]

**Comment by jsturdy** [comment]
Is the "by eye" method the same that was used for the other LUTs?  Otherwise, you could feed this metadata into the phase finding algorithm

**Comment by bdorney** [comment]
> Is the "by eye" method the same that was used for the other LUTs? Otherwise, you could feed this metadata into the phase finding algorithm

Yes the original LUT was made by eye as well; but indeed yes we could send the data into the phase finding algorithm.  Do you think we would significantly gain here?

**Comment by lpetre-ulb** [comment]
Moreover there is no straightforward way of using the phase finding algorithm since it is fully embedded inside `testConnectivity.py`. I was thinking to use the algorithm the program requested in https://github.com/cms-gem-daq-project/gem-plotting-tools/issues/232 But in which repository should the algorithm go? Maybe in `gem-plotting-tools` since it is already required by `vfatqc-python-scripts`? How to deal with the "all phases good" then?

**Review by mexanick — COMMENTED** [review]
cursory

**Pull request merged**
