### PR TITLE
New Feature: sbit rate scan considers all links at once

### PR DESCRIPTION
**Pull request by bdorney**
## Description

Requires:

https://github.com/cms-gem-daq-project/xhal/pull/105
https://github.com/cms-gem-daq-project/ctp7_modules/pull/102

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

Allows multiple links to be scanned simultaneously; greatly decreases test time needed.

## How Has This Been Tested?

See discussion here: https://github.com/cms-gem-daq-project/vfatqc-python-scripts/pull/231

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by mexanick — DISMISSED** [review]

**Comment by mexanick** [comment]
looks this branch requires a rebase

**Comment by bdorney** [comment]
> looks this branch requires a rebase

Done

**Review by jsturdy — DISMISSED** [review]
Cursory

**Comment by jsturdy** [comment]
@bdorney needs conflict resolution during `rebase`

**Comment by bdorney** [comment]
rebase performed and conflicts resolved.

**Review by jsturdy — APPROVED** [review]
Cursory

**Review by mexanick — APPROVED** [review]

**Pull request merged**
