### PR TITLE
[WIP] Implement RPC methods for configuring the GBTX's

### PR DESCRIPTION
**Pull request by lpetre-ulb**
## Description

This is the `cmsgemos`, branch `generic-amc-RPC-v3-short-term`, part of the [corresponding PR](https://github.com/cms-gem-daq-project/ctp7_modules/pull/75) in `ctp7_modules` of which it depends.

See the parent PR for more informations.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bdorney** [comment]
Why is this being implemented here in gempython?  This is a hardware access tool and should not reside on this level.

As a python tool I see this only as appropriate to `reg_utils`.

**Comment by lpetre-ulb** [comment]
I followed what was done for the DAC scans, ... The only part in `gempython` is the wrapping from `xhal` to Python. The actual script is in `reg_utils`, but it might not be the best place. This organisation also seems to follow the one described (in the short term branches) by @jsturdy : https://github.com/cms-gem-daq-project/reg_utils/pull/42#issuecomment-444922907

**Comment by bdorney** [comment]
> I followed what was done for the DAC scans, ... The only part in `gempython` is the wrapping from `xhal` to Python. The actual script is in `reg_utils`, but it might not be the best place. This organisation also seems to follow the one described (in the short term branches) by @jsturdy : [cms-gem-daq-project/reg_utils#42 (comment)](https://github.com/cms-gem-daq-project/reg_utils/pull/42#issuecomment-444922907)

The issue is that you've made a low level repository depend on a high level repository; `reg_utils` was designed to be a agnostic backend SW tool that featured low level support (e.g. atomic transactions only) that other repo's are built on top of.

The short term branch functionality is fine; but we still need to keep the dependencies clear.

**Comment by bdorney** [comment]
Given functionality is provided by https://github.com/cms-gem-daq-project/xhal/pull/102 should we close this PR?

**Comment by lpetre-ulb** [comment]
I think we can indeed close this PR because it has been super-seeded by a different tool. When (and if)  `cmsgemos` will include the code from `xHAL legacyPreBoost`, it would require a new PR anyway.

**Pull request closed without merging**
