### PR TITLE
[gemonlinedb] Core online DB developments

### PR DESCRIPTION
**Pull request by jsturdy**
## Description
PR to merge @lmoureaux's `gemonlinedb` developments into `develop` to allow parallel developments to continue from this core

### Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Motivation and Context
Several features in the pipeline depend on the fundamental thrust of the `gemonlinedb` development, but not on the second phase, so this PR will merge the core functionality in, and allow the second phase to continue on `feature/gemonlinedb`

## How Has This Been Tested?
Previous PRs: #222, #225, #227, #231, #237, #238, #239, #241, #242, #243

### CODE REVIEW

**Comment by jsturdy** [comment]
Rebasing `feature/gemonlindb` onto `develop` to resolve out-of-date

**Comment by mexanick** [comment]
ok, everything looks fine except codacy review, which should be dismissed in this case.
However the web-interface sees it as outdated for some reason

**Comment by mexanick** [comment]
actually I don't see the rebase, only a message about it))

**Comment by lmoureaux** [comment]
@jsturdy Even if I had one I could rebase it since you gave appropriate notice. You can nuke `feature/gemonlinedb`.

**Comment by jsturdy** [comment]
OK, @mexanick, rebased
After some thought, here's what I will do:
* click merge in this PR
* create `release/cmsgemos-1.1.X`
  * modify necessary version info
  * create PR to `master`, merge with `squash` strategy
* manually do
```shell
git co develop
git merge --ff-only release/cmsgemos-1.1.X`
git push gemdaq develop:develop
```
* rebase `feature/add-xhal-interfaces-to-hwdevices` and update #245 (will squash some of the commits to clean up the history)
  * merge 
* recreate `feature/gemonlinedb`
* rebase `feature/gemcalib`

**Pull request merged**
