### PR TITLE
[feature] Add GBTX configuration objects

### PR DESCRIPTION
**Pull request by lmoureaux**
## Description

Add GBTX configuration objects as children of OH configuration. The list of registers was taken from [the reference manual](https://espace.cern.ch/GBT-Project/GBTX/Manuals/gbtxManual.pdf) and names converted to UPPER_CASE for storage in the DB. The two registers without a name in the manual are called UNNAMED_REGISTER_0 and UNNAMED_REGISTER_1.

`parseDef.py` was updated to support 1D arrays of registers in the form `reg0`, `reg1`, etc. This greatly simplifies the JSON files for AMC, OH and GTBX configurations.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

As was discussed offline, we want to store the GBTX configuration in the DB.

## How Has This Been Tested?

Automated tests pass.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jsturdy** [comment]
All field names satisfy Oracle DB max length requirements?

**Comment by lmoureaux** [comment]
> All field names satisfy Oracle DB max length requirements?

If what I find on the Web (30 characters) is correct, they do.

**Comment by jsturdy** [comment]
Let's hold this until the DB guys create the new table, to see if we should restructure anything on this side

**Comment by lmoureaux** [comment]
Rebased.

**Review by jsturdy — APPROVED** [review]

**Pull request merged**
