### PR TITLE
[bugfix] Fix #291: Invalid default value in HwVFAT::stopCalPulses

### LINKED ISSUE #291: Invalid default value in `HwVFAT::stopCalPulses`
## Brief summary of issue

The default value of `chanMax` in `HwVFAT::stopCalPulses` is an invalid value (128) :

https://github.com/cms-gem-daq-project/cmsgemos/blob/48e2f269dac0947be0101d2a9f0d943752e2ce61/gempython/tools/vfat_user_functions_xhal.py#L265

Therefore, when called without arguments, errors are seen in the CTP7 log file and reported to the user through the `error` RPC message key :

``` bash
Jun 21 15:13:10 CTP7 local0.err rpcsvc[28472]: optohybrid.stopCalPulse2AllChannels: Register GEM_AMC.OH.OH8.GEB.VFAT0.VFAT_CHANNELS.CHANNEL128.CALPULSE_ENABLE key not found
```

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

Default arguments should not be invalid values.

## Current Behavior

`chanMax` default value is an invalid value : 128

### Steps to Reproduce (for bugs)

1. Call `HwVFAT::stopCalPulses` with the default arguments.

## Possible Solution (for bugs)

Change the default value of `chanMax` from 128 to 127.

## Context

Prints out error messages in the CTP7 log file :
``` bash
Jun 21 15:13:10 CTP7 local0.err rpcsvc[28472]: optohybrid.stopCalPulse2AllChannels: Register GEM_AMC.OH.OH8.GEB.VFAT0.VFAT_CHANNELS.CHANNEL128.CALPULSE_ENABLE key not found
Jun 21 15:13:10 CTP7 local0.err rpcsvc[28472]: optohybrid.stopCalPulse2AllChannels: Register GEM_AMC.OH.OH8.GEB.VFAT1.VFAT_CHANNELS.CHANNEL128.CALPULSE_ENABLE key not found
Jun 21 15:13:10 CTP7 local0.err rpcsvc[28472]: optohybrid.stopCalPulse2AllChannels: Register GEM_AMC.OH.OH8.GEB.VFAT2.VFAT_CHANNELS.CHANNEL128.CALPULSE_ENABLE key not found
Jun 21 15:13:10 CTP7 local0.err rpcsvc[28472]: optohybrid.stopCalPulse2AllChannels: Register GEM_AMC.OH.OH8.GEB.VFAT3.VFAT_CHANNELS.CHANNEL128.CALPULSE_ENABLE key not found
Jun 21 15:13:10 CTP7 local0.err rpcsvc[28472]: optohybrid.stopCalPulse2AllChannels: Register GEM_AMC.OH.OH8.GEB.VFAT4.VFAT_CHANNELS.CHANNEL128.CALPULSE_ENABLE key not found
Jun 21 15:13:10 CTP7 local0.err rpcsvc[28472]: optohybrid.stopCalPulse2AllChannels: Register GEM_AMC.OH.OH8.GEB.VFAT5.VFAT_CHANNELS.CHANNEL128.CALPULSE_ENABLE key not found
Jun 21 15:13:10 CTP7 local0.err rpcsvc[28472]: optohybrid.stopCalPulse2AllChannels: Register GEM_AMC.OH.OH8.GEB.VFAT6.VFAT_CHANNELS.CHANNEL128.CALPULSE_ENABLE key not found
Jun 21 15:13:10 CTP7 local0.err rpcsvc[28472]: optohybrid.stopCalPulse2AllChannels: Register GEM_AMC.OH.OH8.GEB.VFAT7.VFAT_CHANNELS.CHANNEL128.CALPULSE_ENABLE key not found
Jun 21 15:13:10 CTP7 local0.err rpcsvc[28472]: optohybrid.stopCalPulse2AllChannels: Register GEM_AMC.OH.OH8.GEB.VFAT8.VFAT_CHANNELS.CHANNEL128.CALPULSE_ENABLE key not found
Jun 21 15:13:10 CTP7 local0.err rpcsvc[28472]: optohybrid.stopCalPulse2AllChannels: Register GEM_AMC.OH.OH8.GEB.VFAT9.VFAT_CHANNELS.CHANNEL128.CALPULSE_ENABLE key not found
Jun 21 15:13:10 CTP7 local0.err rpcsvc[28472]: optohybrid.stopCalPulse2AllChannels: Register GEM_AMC.OH.OH8.GEB.VFAT10.VFAT_CHANNELS.CHANNEL128.CALPULSE_ENABLE key not found
Jun 21 15:13:10 CTP7 local0.err rpcsvc[28472]: optohybrid.stopCalPulse2AllChannels: Register GEM_AMC.OH.OH8.GEB.VFAT11.VFAT_CHANNELS.CHANNEL128.CALPULSE_ENABLE key not found
Jun 21 15:13:10 CTP7 local0.err rpcsvc[28472]: optohybrid.stopCalPulse2AllChannels: Register GEM_AMC.OH.OH8.GEB.VFAT12.VFAT_CHANNELS.CHANNEL128.CALPULSE_ENABLE key not found
[...]
```

## Your Environment

* Version used: https://github.com/cms-gem-daq-project/cmsgemos/commit/48e2f269dac0947be0101d2a9f0d943752e2ce61

### PR DESCRIPTION
**Pull request by bdorney**
## Description

Addresses issue #291 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

See issue referenced above.

## How Has This Been Tested?

Change was trivial.

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jsturdy** [comment]
Can people now and in the future create a succinct PR title (referencing an issue is :+1:, but simply saying that the PR title is "Addresses issue X" is not super helpful when looking back through the graph)
(something I will also make more clear in future guideline, as mentioned in a different PR)

**Comment by bdorney** [comment]
> Can people now and in the future create a succinct PR title (referencing an issue is 👍, but simply saying that the PR title is "Addresses issue X" is not super helpful when looking back through the graph)
> (something I will also make more clear in future guideline, as mentioned in a different PR)


Sorry; on the web GUI such commit messages are recognized and github provides a hyperlink to the issue at hand.  I could see how in command line this could be ambiguous however.

If this is merged with "squash and merge" the maintainer can change the commit message.

**Review by lpetre-ulb — APPROVED** [review]
trivial change

**Comment by jsturdy** [comment]
Needs rebase

**Pull request closed without merging**
