### PR TITLE
Populate configuration objects from TStore result

### PR DESCRIPTION
**Pull request by lmoureaux**
## Description

This adds a static function template `DBInterface::convertRow` that converts a `xdata::Table::Row` into a configuration object and tests that pull data from the database.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

Requested in #235

## How Has This Been Tested?

Tests pass. See `tests/testTStoreSerialization.cc`.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by lmoureaux** [comment]
@mexanick Please review this one before the [WIP] #238 that was built on top of it ;-)

**Comment by lmoureaux** [comment]
> Why should we have cases where a valid integer is not stored as `int` and must be stored as `string`?

I can't see a valid use case, but that's how the DB is constructed atm. I can change the software if the DB is updated, but I need to support the current layout somehow.

**Comment by jsturdy** [comment]
Merging blocked by #238 for sequential (better in future to branch from same parent, and rebase once other features have merged, unless strictly dependent on everything in a separate feature PR)

**Comment by lmoureaux** [comment]
Here's how TStore chooses the type based on parameters of the `NUMBER` type `precision` and `scale` [1]:
```C++
if (scale==0) { //if it's an integer
    if (precision<std::log10((long double)INT_MAX)) return "int";
         return "string";
    } else {
        if (precision<=FLT_DIG) return "float";
        if (precision<=DBL_DIG) return "double";
            return "string";
     }
}
```

Most registers are stored in the database are with `precision=10` and `scale=0`. This corresponds to numbers with at most 10 digits, covering a range slightly larger than 32 bits can offer. This means that the expression `precision<std::log10((long double)INT_MAX)` evaluates as `false` and the type deduced by `TStore` is `string`.

I definitely need to update `std::stoi` -> `std::stoul` and add bounds checks since I store values as `std::uint32_t`, but I can't do much more.

[1] `daq-tstoreutils-3.1.2-1.cmsos14.centos7.gcc4_8_5.src.rpm`: `/usr/local/src/xdaq/baseline14/daq/tstore/utils/src/common/OracleConnection.cc` lines 487+

**Comment by jsturdy** [comment]
> I definitely need to update `std::stoi` -> `std::stoul` and add bounds checks since I store values as `std::uint32_t`, but I can't do much more.

Every setting that we're pulling out of the DB will be a register value, so at most a 32-bit unsigned.
In some cases they'll be 8- or 16-bit, but I don't know if there's a strong reason to specialize that further than the 32-bit in the `TStore` conversion step...

**Comment by lmoureaux** [comment]
> In some cases they'll be 8- or 16-bit

These are the only cases where the `TStore` conversion is actually useful.

> I don't know if there's a strong reason to specialize that further than the 32-bit in the `TStore` conversion step

1. Because the `TStore` conversion is always 32 bits signed, it cannot handle all possible unsigned values on 32 bits.
2. Since DB types don't map directly to C++ types, the `TStore` interface isn't the most adapted and fails to hide some implementation details. The conversion from `string` is a workaround. More details [in the code](https://github.com/cms-gem-daq-project/cmsgemos/blob/bf681b0090b83fd9d299c60bb4d0ec1ac2157b9c/gemonlinedb/src/common/DBInterface.cc#L16).

**Comment by jsturdy** [comment]
@lmoureaux, can you rebase this once #239 is merged?

**Comment by lmoureaux** [comment]
Rebased.

**Comment by jsturdy** [comment]
Oops, I think you were too quick, you rebased on top of #238, not #239

**Comment by lmoureaux** [comment]
Ooops

**Comment by lmoureaux** [comment]
Rebased again.

**Pull request merged**
