### PR TITLE
HwVFAT::biasAllVFATs(...) will now throw an exception if RPC response is nonzero (Implementing Feature Request #295)

### LINKED ISSUE #295: Feature Request: `HwVFAT::biasAllVFATs(...)` throws exception if RPC Error Code != 0
## Brief summary of issue

Would like `HwVFAT::biasAllVFATs` to check the RPC response and raise an exception if it is nonzero.

Target branch is [`generic-AMC-RPC-v3-short-term`](https://github.com/cms-gem-daq-project/cmsgemos/tree/generic-amc-RPC-v3-short-term)

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior

Change lines:

https://github.com/cms-gem-daq-project/cmsgemos/blob/0dedd4017e1f61096734c8ce0cd16262d9134c85/gempython/tools/vfat_user_functions_xhal.py#L86-L96

To:

```python
        # HW Dependent Configuration
        if self.parentOH.parentAMC.fwVersion > 2:
            # Baseline config
            rpcResp = self.confVFAT3s(self.parentOH.link,mask)
            if rpcResp != 0:
                raise Exception("{}RPC response was non-zero, failed to configure VFATs on OH{}{}".format(colors.RED,self.parentOH.link,colors.ENDC))

            # Run mode
            if(enable):
                self.writeAllVFATs("CFG_RUN",0x1,mask)
            else:
                self.writeAllVFATs("CFG_RUN",0x0,mask)
        else:
```

This will ensure a failure to configure is properly reported.

## Current Behavior

`HwVFAT::biasAllVFATs(...)` will launch the following:

https://github.com/cms-gem-daq-project/cmsgemos/blob/0dedd4017e1f61096734c8ce0cd16262d9134c85/gempython/tools/vfat_user_functions_xhal.py#L85-L109

Which will call the `xhal` function from the DAQ machine:

https://github.com/cms-gem-daq-project/xhal/blob/721e3e81684457d6d2a74d50b603aa72a720de9b/xhalcore/src/common/rpc_manager/vfat3.cc#L20-L24

And if the `error` key is detected this will return 1 instead of 0. 

However in `HwVFAT::biasAllVFATs` there's no check if this succeed successfully.  And in many cases if this `xhal` function returns 1 the VFATs will *not* be properly configured, for example see the break statement here:

https://github.com/cms-gem-daq-project/ctp7_modules/blob/92eeadc1993dfd85a19cd0a187f76eefb5029e06/src/vfat3.cpp#L148-L162

For sure there will be a terminal output and a "keen" user/developer notices this they can understand a problem occurred:

```bash
[gemuser@gem904qc8daq gemdaq]$ confChamber.py --shelf=1 -s2 -g11
2019.07.09.16.01
Open pickled address table if available  /opt/cmsgemos/etc/maps//amc_address_table_top.pickle...
Initializing AMC gem-shelf01-amc02
opened connection
Configuring VFATs on (shelf1, slot2, OH11) with chamber_vfatDACSettings dictionary values
Caught an error: Error reading settings
biased VFATs on (shelf1, slot2, OH11)
Set CFG_THR_ARM_DAC to 100
Chamber Configured
```

But this will print `Chamber Configured` and no stacktrace is thrown.  So it looks like the call succeeded when it doesn't.

## Context

It's pretty easy to miss a chamber not being configured correctly due to a lack of a check on the RPC response.

## Your Environment

* Version used: 0dedd4017e1f61096734c8ce0cd16262d9134c85

### PR DESCRIPTION
**Pull request by bdorney**
## Description
Closes #295.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

Breaking because:
- RPC errors in `HwVFAT::biasAllVFATs` will cause raise exceptions.

## Motivation and Context

See discussion in #295.

## How Has This Been Tested?

In GEM Production lab.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by bdorney** [comment]
Marking this as blocked since there are unresolved comments on the github issue.

**Comment by bdorney** [comment]
@jsturdy @mexanick I've removed the commits that addressed the closed issue #297 and now this PR only addresses issue #295. 

Ready for re-review.

**Comment by jsturdy** [comment]
Consider how the title will show up in the (automatically generated) changelog and release notes...

**Comment by bdorney** [comment]
> Consider how the title will show up in the (automatically generated) changelog and release notes...

Thanks for explaining the need for a title change and the context; it makes a lot of sense.  I've updated the title accordingly.

**Review by jsturdy — APPROVED** [review]

**Pull request merged**
